apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: main
          image: stefanprodan/podinfo:latest
          ports:
            - name: http
              containerPort: 9898
          livenessProbe:
            httpGet:
              path: /readyz
              port: 9898
          readinessProbe:
            httpGet:
              path: /readyz
              port: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  type: LoadBalancer
  selector:
    app: podinfo
  ports:
    - name: http
      port: 80
      targetPort: http
