name: Kubernetes Comparison 10x

on:
  workflow_dispatch:

jobs:
  comparison:
    name: run-${{ matrix.number }}
    uses: ./.github/workflows/comparison.yaml
    strategy:
      fail-fast: false
      matrix:
        number:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
